apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cnp-operator-any
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  ingress:
    - {}
  egress:
    - {}