apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: local-cluster

servers: 1
agents: 3

kubeAPI:
  host: lc.localhost
  hostIP: "127.0.0.1"
  hostPort: "6443"

subnet: "10.250.0.0/16"

ports:
  - port: 80:8080
    nodeFilters:
      - loadbalancer
  - port: 443:8443
    nodeFilters:
      - loadbalancer

registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"

options:
  k3d:
    wait: true

  k3s:
    nodeLabels:
      - label: "k3s-server=true"
        nodeFilters:
          - server:*
      - label: "k3s-agent=true"
        nodeFilters:
          - agent:*

    extraArgs:
      - arg: --service-cidr=10.248.0.0/16
        nodeFilters:
          - server:*
      - arg: --cluster-cidr=10.249.0.0/16
        nodeFilters:
          - server:*
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
      - arg: --disable-network-policy
        nodeFilters:
          - server:*
      - arg: --disable=kube-proxy
        nodeFilters:
          - server:*
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --node-taint=k3s-controlplane=true:NoSchedule
        nodeFilters:
          - server:*